### ISSUE TITLE
SigRok driver

### ISSUE THREAD

**Issue by djtulan** [gusmanb/logicanalyzer#162]
Hi!

First of all, great work!

How about making a driver for SigRok.

It is a open source platform for all kinds of lab devices.
It also includes a program called PulseView, hat can show results of a logic analyser.

best regards,
Robert

**Comment by gusmanb** [comment]
Witgh Sigrok I could not implement all the special trigger capabilities that the device has, also getting any change to Sigrok in order to get the driver into it can take literally years (I know because of the project pico-analyzer).

If you really want to use Sigrok you can capture with LogicAnalyzer and export the captures, the format is compatible.
