### ISSUE TITLE
False Positives?

### ISSUE THREAD

**Issue by techfox3010** [gusmanb/logicanalyzer#78]
After attempting to run on a machine with Norton, both the .exe and a bunch of the .dll's got flagged and removed as part of remidiation.

**Comment by gusmanb** [comment]
I would say that machine has been infected with a virus called Norton antivirus 😂

Norton is worse than most of the viruses that you can find, that thing destroys apps like crazy.

![imagen](https://github.com/gusmanb/logicanalyzer/assets/4086913/76f427c2-1c75-4bbf-bccc-cba8edbb8dc6)

As you can see except for one dumb engine all the rest flag it as clean, and that engine simply sets it as "generic trojan" because the analyzer can connect to the wifi logic analyzer.
